# 容器化构建服务
apiVersion:  apps/v1
kind: Deployment  # 作用是管理 replicaset-controller
metadata:
  labels:
    app: agent-server
  name: agent-server
  namespace: aido
spec:
  replicas: 3  # 扩容
  revisionHistoryLimit: 3 # 指定可以保留的旧的replicaset数量
  selector:     # 圈定deployment管理的pod范围
    matchLabels:
      app: agent-server
  template:
    metadata:
      labels:
        app: agent-server
      annotations: # 将任何非标识metadata附加到对象
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8023"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - image: registry.devops.cmft/agent/agent-server:20200918-f32ef4b6
        imagePullPolicy: IfNotPresent
        name: cicd-flow 
        envFrom:
        - configMapRef:
            name: aido-configmap
        env:
        - name: MEMORY
          value: "3000"
        - name: HOSTNAME
          value: agent-server
        resources:
          limits:
            cpu: "0"
            memory: 3600Mi
          requests:
            cpu: "0"
            memory: 3600Mi
        readinessProbe:
          tcpSocket:
            port: 8023
          failureThreshold: 3
          initialDelaySeconds: 60
        livenessProbe:
          tcpSocket:
            port: 8023
          failureThreshold: 3
          initialDelaySeconds: 90
        volumeMounts:
        - mountPath: /logs
          name: log-vol
      volumes:
      - name: log-vol
        nfs:
          path: /aido_logs/agent-server
          server: 10.3.60.229
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-harbor
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: agent-server
  namespace: aido
  labels:
    app: agent-server
spec:
  ports:
  - name: http-8023
    port: 8023
    protocol: TCP
    targetPort: 8023
  selector:
    app: agent-server
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: agent-server
  namespace: aido
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agent-server
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Pods
    pods:
      metric:
        name: http_server_requests_seconds
      target:
        type: AverageValue
        averageValue: 50