apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: confluence
  name: confluence
  namespace: aido
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: confluence
  template:
    metadata:
      labels:
        k8s-app: confluence
      name: confluence
      namespace: default
    spec:
      containers:
      - name: confluence
        image: registry.devops.cmft/library/atlassian/confluence-server:7.2.0
        imagePullPolicy: IfNotPresent
        env:
          - name: CATALINA_CONNECTOR_SCHEME
            value: https
          - name: CATALINA_CONNECTOR_PROXYNAME
            value: wiki.devops.cmft
          - name: CATALINA_CONNECTOR_PROXYPORT
            value: "443"
        ports:
          - containerPort: 8090
            name: web
            protocol: TCP
          - containerPort: 8091
            name: extra
            protocol: TCP
        resources:
          limits:
            cpu: 3000m
            memory: 10Gi
          requests:
            cpu: 500m
            memory: 3000Mi
        volumeMounts:
        - name: confluence-data
          mountPath: /var/atlassian/application-data/confluence 
      volumes:
      - name: confluence-data
        nfs:
          path: /data/confluence-repo-data
          server: 10.3.60.229
---
apiVersion: v1
kind: Service
metadata:
  name: confluence
  namespace: aido
  labels:
    k8s-app: confluence
spec:
  selector:
    k8s-app: confluence
  ports:
    - name: web
      protocol: TCP
      port: 8090
      targetPort: 8090
    - name: extra
      protocol: TCP
      port: 8091
      targetPort: 8091