apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: nexus3
  name: nexus3
  namespace: aido
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nexus3
  template:
    metadata:
      labels:
        k8s-app: nexus3
      name: nexus3
      namespace: default
    spec:
      containers:
      - name: nexus3
        image: registry.devops.cmft/library/nexus:3.20.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8081
            name: web
            protocol: TCP
#        livenessProbe:
#          httpGet:
#            path: /
#            port: 8081
#          initialDelaySeconds: 60
#          periodSeconds: 30
#          failureThreshold: 3
#        readinessProbe:
#          httpGet:
#            path: /
#            port: 8081
#          initialDelaySeconds: 90
#          periodSeconds: 30
#          failureThreshold: 3
        resources:
          limits:
            cpu: 3000m
            memory: 10Gi
          requests:
            cpu: 500m
            memory: 3000Mi
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
      volumes:
      - name: nexus-data
        nfs:
          path: /data/nexus-repo-data
          server: 10.3.60.229
---
apiVersion: v1
kind: Service
metadata:
  name: nexus3
  namespace: aido
  labels:
    k8s-app: nexus3
spec:
  selector:
    k8s-app: nexus3
  ports:
    - name: web
      protocol: TCP
      port: 8081
      targetPort: 8081