apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: vscode-console
  name: vscode-console
  namespace: aido
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: vscode-console
  template:
    metadata:
      labels:
        k8s-app: vscode-console
      name: vscode-console
      namespace: aido
    spec:
      containers:
      - name: vscode-console
        image: registry.devops.cmft/vscode/vscode-console:20201027-52bfd0e6
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: aido-configmap
        resources:
          limits:
            cpu: 5000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - mountPath: /data/devops_vol/vscode_data
          name: data-vol
      nodeName: 10.3.60.233
      volumes:
      - name: data-vol
        nfs:
          path: /data/devops_vol/vscode_data
          server: 10.3.60.229
---
apiVersion: v1
kind: Service
metadata:
  name: vscode-console
  namespace: aido
  labels:
    k8s-app: vscode-console
spec:
  selector:
    k8s-app: vscode-console
  ports:
    - name: console-console
      protocol: TCP
      port: 12345
      targetPort: 12345